SELECT P2ACE,	P1NETPOINTWON,	P1BREAKPOINTWON,	P1ACE,	P1FIRSTSRVWON,	P1FIRSTSRVIN,	P2UNFERR,	P1DOUBLEFAULT,	P2NETPOINT,	P1FORCEDERROR,	P2BREAKPOINTMISSED,	P2NETPOINTWON,	P2DOUBLEFAULT,	P2SECONDSRVIN,	P2FIRSTSRVIN,	P2SECONDSRVWON,	P2WINNER,	P2BREAKPOINTWON,	P1SECONDSRVIN,	P1WINNER,	P2BREAKPOINT,	P2FORCEDERROR,	P1NETPOINT,	P1BREAKPOINTMISSED,	P1UNFERR,	P2FIRSTSRVWON,	P1BREAKPOINT,	P1SECONDSRVWON,	SURFACE, CASE(WINNER) WHEN 1 THEN 'Player1' WHEN 2 THEN 'Player2' END AS WINNER

FROM 
        ALL_TOURNAMENTS_2011_2015 AS A
    INNER JOIN
        SURFACE_BY_TOURNAMENT AS B
        ON
            A.TOURNAMENT = B.TOURNAMENT
WHERE WINNER <> ''